name: "build"

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [released]

permissions:
  actions: "write"
  contents: "write"
  id-token: "write"

jobs:
  call-build:
    uses: "KyoriPowered/ci-cookbook/.github/workflows/java-ci.yaml@e77e68e0bee07333adf9ea66f8da5fa1e1363003" # 2025.10.17
    with:
      publish_releases: true
      publish_release_javadoc: true
      javadoc_deploy_prefix: "platform/"
    secrets:
      DEPLOYMENT_APP_ID: "${{ secrets.DEPLOYMENT_APP_ID }}"
      DEPLOYMENT_APP_SECRET: "${{ secrets.DEPLOYMENT_APP_SECRET }}"
      publishing_env_vars: |
          ORG_GRADLE_PROJECT_sonatypeUsername="${{ secrets.ADVENTURE_SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword="${{ secrets.ADVENTURE_SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriSigningKey="${{ secrets.ADVENTURE_GPG_KEY }}"
          ORG_GRADLE_PROJECT_kyoriSigningPassword="${{ secrets.ADVENTURE_GPG_PASSWORD }}"

